# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# theme: jekyll-theme-so-simple
# remote_theme: mmistakes/so-simple-theme

locale: ko-KR
title: "huginn and muninn"
description: "books quotes thoughts inspirations"
baseurl: "blog"
url: "https://huginnamuninn.github.io"
logo: "/images/logo.png"
date_format: "%Y/%m/%d"
read_time: false
words_per_minute: # 200
mathjax:
  enable: false
  combo: "tex-svg"
  tags: "ams"

google_analytics: ""
disqus:
  shortname: "huginnamuninn"
twitter:
  username: ""
google_site_verification: ""

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 9
paginate_path: /page:num/

# Search
search_full_content: true

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # Recipe defaults
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      comments: true
      share: true

# Site Author
# author:
#  name: Michael Rose
#  picture: /images/michael-rose-photo.jpg
#  email:
#  twitter: 
#  links:
#    - title: Twitter
#      url: 
#      icon: fab fa-twitter-square
#    - title: Instagram
#      url: https://instagram.com/huginnmm
#      icon: fab fa-instagram
#    - title: GitHub
#      url: https://github.com/huginnamuninn
#      icon: fab fa-github-square

# Footer Links
footer_links:
  - title: Feed
    url: atom.xml
    icon: fa-solid fa-rss
  - title: Blog
    url: https://huginnamuninn.github.io
    icon: fa-solid fa-quote-right
  - title: Instagram
    url: https://instagram.com/huginnmm
    icon: fa-brands fa-instagram
  - title: GitHub
    url: https://github.com/huginnamuninn
    icon: fa-brands fa-github-alt
  - title: Jekyll
    url: https://jekyllrb.com
    icon: fa-solid fa-code
  - title: So Simple
    url: https://github.com/mmistakes/so-simple-theme
    icon: fa-solid fa-code-commit
